### ISSUE TITLE
Error when running with the the TBB threading layer

### ISSUE THREAD

**Issue by thurber** [IMMM-SFA/mosartwmpy#65]
Reported by @erexer: When running `mosartwmpy` with `numba` using the TBB threading layer, an error occurs when trying to read the TypedDict that represents the reservoir/grid cell dependency database. Need to either force `workqueue` as the threading layer or figure out what's causing TBB layer to fail. It might be that the code is expecting the threads to share memory, but the TBB threads do not share memory.

**Comment by erexer** [comment]
Here's the error:
```bash
Failed to complete timestep; see below for stacktrace.
Traceback (most recent call last):
  File "/mosartwmpy/venv/lib/python3.8/site-packages/numba/typed/dictobject.py", line 739, in impl
    raise KeyError()
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mosartwmpy/mosartwmpy/model.py", line 191, in update
    update(self.state, self.grid, self.parameters, self.config, self.current_time)
  File "/mosartwmpy/mosartwmpy/update/update.py", line 262, in update
    extraction_regulated_flow(
SystemError: CPUDispatcher(<function extraction_regulated_flow at 0x7fea89568c10>) returned a result with an error set
Traceback (most recent call last):
  File "/mosartwmpy/venv/lib/python3.8/site-packages/numba/typed/dictobject.py", line 739, in impl
    raise KeyError()
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tutorial.py", line 11, in <module>
    mosart_wm.update()
  File "/mosartwmpy/mosartwmpy/model.py", line 196, in update
    raise e
  File "/mosartwmpy/mosartwmpy/model.py", line 191, in update
    update(self.state, self.grid, self.parameters, self.config, self.current_time)
  File "/mosartwmpy/mosartwmpy/update/update.py", line 262, in update
    extraction_regulated_flow(
SystemError: CPUDispatcher(<function extraction_regulated_flow at 0x7fea89568c10>) returned a result with an error set
```
